const datos = [
  {
    img: "https://fwmedia.fandomwire.com/wp-content/uploads/2023/07/03114350/20230703_164251_0000.png",
    title: "Rise of the Ronin",
    category: "Lucha, Samurais",
    votes: 5,
    comment: "Es genial",
  },
  {
    img: "https://www.lavanguardia.com/files/og_thumbnail/uploads/2020/04/01/5fa9039de905f.png",
    title: "Persona 5 Royal",
    category: "Anime, Mascaras",
    votes: 5,
    comment: "Muy divertido",
  },
  {
    img: "https://www.hogwartslegacy.com/images/share.jpg",
    title: "Hogwarts Legacy Standard",
    category: "Trama, Legendario",
    votes: 5,
    comment: "¡Es como estar dentro de Hogwarts!",
  },
  {
    img: "https://cdn-products.eneba.com/resized-products/faaTwmRiXM6cCnaCYWJ8f6VM3qTpWm7o0KlcqsnTRdw_350x200_1x-0.png",
    title: "Northgard",
    category: "Aventura, Acción, Fantasía",
    votes: 4,
    comment: "Increíble mundo abierto",
  },
  {
    img: "https://a.allegroimg.com/original/12d07a/136d0b814ee19c9e9719d1257203",
    title: "Elden ring edicion standard",
    category: "Aventura, Acción, Fantasía",
    votes: 4,
    comment: "Increíble mundo abierto",
  },
  {
    img: "https://assetsio.gnwcdn.com/FtnzBY_WYAMMYpj.jpg?width=1600&height=900&fit=crop&quality=100&format=png&enable=upscale&auto=webp",
    title: "Final Fantasy XVI",
    category: "Acción, Aventura, Fantasia",
    votes: 5,
    comment: "Los clasicos mejorados",
  },
  {
    img: "https://i0.wp.com/blog.vsgamers.es/wp-content/uploads/2020/11/cyberpunk-2077-versus-gamers.png?fit=832%2C554&ssl=1",
    title: "Cyberpunk 2077",
    category: "Acción, Mundo abierto, Cyberpunk",
    votes: 3,
    comment: "Interesante",
  },
  {
    img: "https://soloauto.net/wp-content/uploads/2023/05/lanzamiento_F1_23.jpg",
    title: "F1 23",
    category: "Carreras",
    votes: 2,
    comment: "Hay otros mejores",
  },
  {
    img: "https://www.desconsolados.com/wp-content/uploads/2022/08/Do-Not-Open.jpeg",
    title: "Do not open",
    category: "Terror",
    votes: 0,
    comment: "Los graficos son bastante mejorables",
  },
];
