const datos = [
  {
    img: "https://canarias.worten.es/i/d0481baab718b86b76d295f9b0602c9c052a0285",
    title: "RISE OF THE RONIN",
    category: "Lucha, Samurais",
    votes: 5,
    comment: "Es genial",
  },
  {
    img: "https://cdn-products.eneba.com/resized-products/JX_LogDQuOTQFMcsSO31Bm11mrAX-f8UYR0gKgDEgRM_350x200_3x-0.png",
    title: "Persona 5 Royal",
    category: "Anime, Mascaras",
    votes: 5,
    comment: "Muy divertido",
  },
  {
    img: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_99222767/fee_786_587_png",
    title: "Hogwarts Legacy Standard",
    category: "Trama, Legendario",
    votes: 5,
    comment: "¡Es como estar dentro de Hogwarts!",
  },
  {
    img: "https://cdn-products.eneba.com/resized-products/faaTwmRiXM6cCnaCYWJ8f6VM3qTpWm7o0KlcqsnTRdw_350x200_1x-0.png",
    title: "Northgard",
    category: "Aventura, Acción, Fantasía",
    votes: 4,
    comment: "Increíble mundo abierto",
  },
  {
    img: "https://www.games2egypt.com/Images/Products/36506?fileFormat=1&height=500",
    title: "Elden ring edicion standard",
    category: "Aventura, Acción, Fantasía",
    votes: 4,
    comment: "Increíble mundo abierto",
  },
  {
    img: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_100469587/fee_786_587_png",
    title: "Final Fantasy XVI",
    category: "Acción, Aventura, Fantasia",
    votes: 5,
    comment: "Los clasicos mejorados",
  },
  {
    img: "https://www.worten.es/i/51d15596ea83925c924375d70a31c79b3dd809fd.jpg",
    title: "Cyberpunk 2077",
    category: "Acción, Mundo abierto, Cyberpunk",
    votes: 3,
    comment: "Interesante pero con problemas de rendimiento",
  },
  {
    img: "https://www.skygames.com.pk/wp-content/uploads/2023/06/f1-2023-ps4.png",
    title: "F1 23",
    category: "Carreras",
    votes: 2,
    comment: "Hay otros mejores",
  },
  {
    img: "https://kurogami.com/img/productos/4f/34/do-not-open-ps4-psvr.png",
    title: "Do not open",
    category: "Terror",
    votes: 0,
    comment: "Los graficos son bastante mejorables",
  },
];
